### ISSUE TITLE
ttree.d doesn't build with 2.067.0-b2

### ISSUE THREAD

**Issue by jwhear** [economicmodeling/containers#8]
```
containers/src/containers/ttree.d(491): Error: template instance sort!_less template 'sort' is not defined
containers/src/containers/ttree.d(528): Error: template instance sort!_less template 'sort' is not defined
containers/src/containers/ttree.d(491): Error: template instance sort!_less template 'sort' is not defined
containers/src/containers/ttree.d(528): Error: template instance sort!_less template 'sort' is not defined
src/autocomplete.d(167): Error: template instance containers.ttree.TTree!(SearchResult, false, "a < b", true, 64LU) error instantiating
src/autocomplete.d(131): Error: function autocomplete.symbolSearch no return exp; or assert(0); at end of function
containers/src/containers/ttree.d(491): Error: template instance sort!_less template 'sort' is not defined
containers/src/containers/ttree.d(528): Error: template instance sort!_less template 'sort' is not defined
```
